[project]
name = "customer-churn-prediction-service"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "youngboy21178", email = "maksym.melnyk.o.2007@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=1.0.2",
]

[project.scripts]
customer-churn-prediction-service = "customer_churn_prediction_service:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

